// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_RAWC_BDM1NI_H_
#define _TAO_IDL_RAWC_BDM1NI_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace PapyrusrtDDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_PAPYRUSRTDDS_BUFFERTYPE_CH_)
#define _PAPYRUSRTDDS_BUFFERTYPE_CH_

  class BufferType;

  typedef
    ::TAO_FixedSeq_Var_T<
        BufferType
      >
    BufferType_var;

  typedef
    ::TAO_Seq_Out_T<
        BufferType
      >
    BufferType_out;

  class  BufferType
    : public
        ::TAO::unbounded_value_sequence<
            ::CORBA::Octet
          >
  {
  public:
    BufferType (void);
    BufferType ( ::CORBA::ULong max);
    BufferType (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Octet* buffer,
      ::CORBA::Boolean release = false);
    BufferType (const BufferType &);
    virtual ~BufferType (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef BufferType_var _var_type;
    typedef BufferType_out _out_type;

    static void _tao_any_destructor (void *);

    

#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
    BufferType (
        ::CORBA::ULong length,
        const ACE_Message_Block* mb
      )
      : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_BufferType;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct RawBuffer;

  typedef
    ::TAO_Var_Var_T<
        RawBuffer
      >
    RawBuffer_var;

  typedef
    ::TAO_Out_T<
        RawBuffer
      >
    RawBuffer_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  RawBuffer
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef RawBuffer_var _var_type;
    typedef RawBuffer_out _out_type;

    static void _tao_any_destructor (void *);
    
    PapyrusrtDDS::BufferType buffer;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_RawBuffer;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module PapyrusrtDDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::PapyrusrtDDS::BufferType>
    : public
        Var_Size_Arg_Traits_T<
            ::PapyrusrtDDS::BufferType,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::PapyrusrtDDS::RawBuffer>
    : public
        Var_Size_Arg_Traits_T<
            ::PapyrusrtDDS::RawBuffer,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:50



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace PapyrusrtDDS
{
   void operator<<= ( ::CORBA::Any &, const ::PapyrusrtDDS::BufferType &); // copying version
   void operator<<= ( ::CORBA::Any &, ::PapyrusrtDDS::BufferType*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::PapyrusrtDDS::BufferType *&); // deprecated
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::PapyrusrtDDS::BufferType *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const PapyrusrtDDS::BufferType &); // copying version
 void operator<<= ( ::CORBA::Any &, PapyrusrtDDS::BufferType*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, PapyrusrtDDS::BufferType *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const PapyrusrtDDS::BufferType *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace PapyrusrtDDS
{
   void operator<<= (::CORBA::Any &, const ::PapyrusrtDDS::RawBuffer &); // copying version
   void operator<<= (::CORBA::Any &, ::PapyrusrtDDS::RawBuffer*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::PapyrusrtDDS::RawBuffer *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::PapyrusrtDDS::RawBuffer *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const PapyrusrtDDS::RawBuffer &); // copying version
 void operator<<= (::CORBA::Any &, PapyrusrtDDS::RawBuffer*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, PapyrusrtDDS::RawBuffer *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const PapyrusrtDDS::RawBuffer *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_PapyrusrtDDS_BufferType_H_
#define _TAO_CDR_OP_PapyrusrtDDS_BufferType_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const PapyrusrtDDS::BufferType &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    PapyrusrtDDS::BufferType &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_PapyrusrtDDS_BufferType_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const PapyrusrtDDS::RawBuffer &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, PapyrusrtDDS::RawBuffer &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "RawC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

