/* -*- C++ -*- */
/* Generated by opendds_idl version 3.12.2 (ACE version 6.2a_p14) running on input file Raw.idl */
#ifndef OPENDDS_IDL_GENERATED_RAWTYPESUPPORTIMPL_H_CETDP8
#define OPENDDS_IDL_GENERATED_RAWTYPESUPPORTIMPL_H_CETDP8
#include "RawC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "RawTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: PapyrusrtDDS */



/* Begin TYPEDEF: BufferType */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const PapyrusrtDDS::BufferType& seq, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const PapyrusrtDDS::BufferType& seq);

bool operator>>(Serializer& strm, PapyrusrtDDS::BufferType& seq);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool gen_skip_over(Serializer& ser, PapyrusrtDDS::BufferType*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End TYPEDEF: BufferType */


/* Begin STRUCT: RawBuffer */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const PapyrusrtDDS::RawBuffer& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const PapyrusrtDDS::RawBuffer& stru);

bool operator>>(Serializer& strm, PapyrusrtDDS::RawBuffer& stru);

size_t gen_max_marshaled_size(const PapyrusrtDDS::RawBuffer& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const PapyrusrtDDS::RawBuffer> stru, bool align);

void gen_find_size(KeyOnly<const PapyrusrtDDS::RawBuffer> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const PapyrusrtDDS::RawBuffer> stru);

bool operator>>(Serializer& strm, KeyOnly<PapyrusrtDDS::RawBuffer> stru);

template <>
struct MarshalTraits<PapyrusrtDDS::RawBuffer> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace PapyrusrtDDS {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  RawBuffer_OpenDDS_KeyLessThan {
  bool operator()(const PapyrusrtDDS::RawBuffer&, const PapyrusrtDDS::RawBuffer&) const
  {
    // Eith no DCPS_DATA_KEYs, return false
    // to allow use of map with just one entry
    return false;
  }
};
}


namespace PapyrusrtDDS {
class RawBufferTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<PapyrusrtDDS::RawBuffer> {
  typedef PapyrusrtDDS::RawBuffer MessageType;
  typedef PapyrusrtDDS::RawBufferSeq MessageSequenceType;
  typedef PapyrusrtDDS::RawBufferTypeSupport TypeSupportType;
  typedef PapyrusrtDDS::RawBufferTypeSupportImpl TypeSupportTypeImpl;
  typedef PapyrusrtDDS::RawBufferDataWriter DataWriterType;
  typedef PapyrusrtDDS::RawBufferDataReader DataReaderType;
  typedef PapyrusrtDDS::RawBuffer_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "PapyrusrtDDS::RawBuffer"; }
  static bool gen_has_key () { return false; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace PapyrusrtDDS {
class  RawBufferTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<RawBufferTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<RawBuffer> TraitsType;
  typedef RawBufferTypeSupport TypeSupportType;
  typedef RawBufferTypeSupport::_var_type _var_type;
  typedef RawBufferTypeSupport::_ptr_type _ptr_type;

  RawBufferTypeSupportImpl() {}
  virtual ~RawBufferTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static RawBufferTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<PapyrusrtDDS::RawBuffer>();
bool gen_skip_over(Serializer& ser, PapyrusrtDDS::RawBuffer*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: RawBuffer */

/* End MODULE: PapyrusrtDDS */
#endif /* OPENDDS_IDL_GENERATED_RAWTYPESUPPORTIMPL_H_CETDP8 */
